# Generated by Django 5.2 on 2025-07-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_email_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='userid',
            new_name='username',
        ),
    ]
